import AVFoundation
import Foundation
import Observation

public struct SubtitleCue: Sendable, Equatable {
    public let start: Duration
    public let end: Duration
    public let text: String
}

public enum VTTParser {
    static let maxCues = 5000

    public static func parse(_ input: String) -> [SubtitleCue] {
        var cues: [SubtitleCue] = []
        let lines = input.replacingOccurrences(of: "\r\n", with: "\n").split(separator: "\n", omittingEmptySubsequences: false)
        var i = 0
        while i < lines.count, cues.count < maxCues {
            let line = lines[i]
            guard let arrow = line.range(of: "-->") else { i += 1; continue }
            let startText = line[..<arrow.lowerBound].trimmingCharacters(in: .whitespaces)
            let endText = line[arrow.upperBound...].trimmingCharacters(in: .whitespaces).split(separator: " ").first.map(String.init) ?? ""
            i += 1
            var textLines: [String] = []
            while i < lines.count, !lines[i].trimmingCharacters(in: .whitespaces).isEmpty {
                textLines.append(String(lines[i])); i += 1
            }
            guard let s = timestamp(startText), let e = timestamp(endText), e > s else { continue }
            let text = clean(textLines.joined(separator: "\n"))
            if !text.isEmpty { cues.append(SubtitleCue(start: s, end: e, text: text)) }
        }
        return cues.sorted { $0.start < $1.start }
    }

    static func timestamp(_ s: String) -> Duration? {
        let parts = s.replacingOccurrences(of: ",", with: ".").split(separator: ":").map(String.init)
        guard parts.count == 2 || parts.count == 3, let sec = Double(parts[parts.count - 1]), let min = Double(parts[parts.count - 2]) else { return nil }
        let hours = parts.count == 3 ? (Double(parts[0]) ?? 0) : 0
        return Duration(seconds: hours * 3600 + min * 60 + sec)
    }

    static func clean(_ s: String) -> String {
        var out = "", inTag = false
        for ch in s {
            if ch == "<" { inTag = true } else if ch == ">" { inTag = false } else if !inTag { out.append(ch) }
        }
        return out.replacingOccurrences(of: "&amp;", with: "&").replacingOccurrences(of: "&lt;", with: "<")
            .replacingOccurrences(of: "&gt;", with: ">").replacingOccurrences(of: "&nbsp;", with: " ")
            .replacingOccurrences(of: "&quot;", with: "\"").replacingOccurrences(of: "&#39;", with: "'")
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }
}

public struct CaptionPreference: Sendable, Equatable {
    public var enabled: Bool
    public var languageCode: String?
    public init(enabled: Bool, languageCode: String?) { self.enabled = enabled; self.languageCode = languageCode }
}

/// Subtitles (ADR §34). Native `AVMediaSelectionGroup` options are used when the stream provides them; otherwise
/// provider caption files are fetched, parsed, and rendered as an overlay.
@MainActor @Observable
public final class SubtitleManager {
    public enum Selection: Equatable, Sendable { case off, external(String), native(String) }
    public struct NativeOption: Identifiable, Equatable, Sendable { public let id: String; public let name: String }

    public private(set) var tracks: [SubtitleTrack] = []
    public private(set) var translations: [LanguageOption] = []
    public private(set) var nativeOptions: [NativeOption] = []
    public private(set) var selection: Selection = .off
    public private(set) var currentText: String?

    @ObservationIgnored private let http: any HTTPClient
    @ObservationIgnored private var cues: [SubtitleCue] = []
    @ObservationIgnored private var loadTask: Task<Void, Never>?
    @ObservationIgnored private var nativeOptionObjects: [String: AVMediaSelectionOption] = [:]
    @ObservationIgnored private var nativeGroup: AVMediaSelectionGroup?
    @ObservationIgnored private weak var playerItem: AVPlayerItem?

    public init(http: any HTTPClient) { self.http = http }

    /// Re-run on every (re)load; the previous selection survives a stream refresh (ADR §49).
    public func configure(resource: PlaybackResource, item: AVPlayerItem?, preference: CaptionPreference) async {
        loadTask?.cancel()
        let previous = selection
        tracks = resource.subtitles
        translations = resource.translationLanguages
        playerItem = item
        cues = []; currentText = nil; selection = .off
        await loadNativeOptions(from: item)

        if case .external(let id) = previous, let t = tracks.first(where: { $0.id == id }) { await select(track: t); return }
        if case .native(let id) = previous, nativeOptions.contains(where: { $0.id == id }) { selectNative(id: id); return }
        guard preference.enabled else { return }
        if let lang = preference.languageCode, let t = tracks.first(where: { $0.languageCode == lang && !$0.isAutoGenerated }) ?? tracks.first(where: { $0.languageCode == lang }) {
            await select(track: t)
        } else if let t = tracks.first(where: { !$0.isAutoGenerated }) ?? tracks.first {
            await select(track: t)
        }
    }

    public func disable() {
        loadTask?.cancel()
        if let item = playerItem, let group = nativeGroup { item.select(nil, in: group) }
        selection = .off; cues = []; currentText = nil
    }

    public func select(track: SubtitleTrack) async {
        loadTask?.cancel()
        if let item = playerItem, let group = nativeGroup { item.select(nil, in: group) }
        selection = .external(track.id); cues = []; currentText = nil
        let url = track.url, client = http
        let task = Task { [weak self] in
            guard let (data, _) = try? await client.data(for: URLRequest(url: url)), !Task.isCancelled,
                  data.count <= 2 * 1024 * 1024, let text = String(data: data, encoding: .utf8) else { return }
            let parsed = VTTParser.parse(text)
            guard !Task.isCancelled else { return }
            self?.cues = parsed
        }
        loadTask = task
        await task.value
    }

    /// "Translated subtitles where available" — the provider translates server-side via a language parameter.
    public func select(translation: LanguageOption, of base: SubtitleTrack) async {
        guard var comps = URLComponents(url: base.url, resolvingAgainstBaseURL: false) else { return }
        comps.queryItems = (comps.queryItems ?? []).filter { $0.name != "tlang" } + [URLQueryItem(name: "tlang", value: translation.code)]
        guard let url = comps.url else { return }
        let translated = SubtitleTrack(id: "\(base.id)>\(translation.code)", languageCode: translation.code, displayName: translation.name,
                                       url: url, isAutoGenerated: base.isAutoGenerated, isTranslation: true)
        await select(track: translated)
    }

    public func selectNative(id: String) {
        guard let item = playerItem, let group = nativeGroup, let option = nativeOptionObjects[id] else { return }
        loadTask?.cancel(); cues = []; currentText = nil
        item.select(option, in: group)
        selection = .native(id)
    }

    /// Cheap binary search; only touches observable state when the visible cue actually changes.
    public func update(position: Duration) {
        guard case .external = selection, !cues.isEmpty else { if currentText != nil { currentText = nil }; return }
        var lo = 0, hi = cues.count - 1, found: Int?
        while lo <= hi {
            let mid = (lo + hi) / 2
            if cues[mid].start <= position { found = mid; lo = mid + 1 } else { hi = mid - 1 }
        }
        let text = found.flatMap { position < cues[$0].end ? cues[$0].text : nil }
        if text != currentText { currentText = text }
    }

    private func loadNativeOptions(from item: AVPlayerItem?) async {
        nativeOptions = []; nativeOptionObjects = [:]; nativeGroup = nil
        guard let asset = item?.asset, let group = try? await asset.loadMediaSelectionGroup(for: .legible) else { return }
        nativeGroup = group
        for (index, option) in group.options.enumerated() {
            let id = "native-\(index)"
            nativeOptionObjects[id] = option
            nativeOptions.append(NativeOption(id: id, name: option.displayName))
        }
    }
}
