import Foundation

public struct MediaStream: Sendable, Hashable, Identifiable {
    public enum Container: String, Sendable, Hashable { case hls, mp4, m4a, webm, other }

    public let id: String
    public let url: URL
    public let container: Container
    public let hasVideo: Bool
    public let hasAudio: Bool
    public let width: Int?
    public let height: Int?
    public let bitrate: Int?
    public let frameRate: Double?
    public let codecs: [String]
    public let isDefaultAudio: Bool

    public init(
        id: String, url: URL, container: Container, hasVideo: Bool, hasAudio: Bool,
        width: Int? = nil, height: Int? = nil, bitrate: Int? = nil, frameRate: Double? = nil,
        codecs: [String] = [], isDefaultAudio: Bool = true
    ) {
        self.id = id; self.url = url; self.container = container; self.hasVideo = hasVideo; self.hasAudio = hasAudio
        self.width = width; self.height = height; self.bitrate = bitrate; self.frameRate = frameRate
        self.codecs = codecs; self.isDefaultAudio = isDefaultAudio
    }

    public var isMuxed: Bool { hasVideo && hasAudio }
    public var isHLS: Bool { container == .hls }

    /// Short side of the frame, so portrait video is labelled by its "p" value like landscape video.
    public var qualityHeight: Int? {
        guard let width, let height else { return height }
        return min(width, height)
    }

    /// Whether AVFoundation can decode this stream with hardware acceleration (ADR §10, §57).
    public var isNativelyPlayable: Bool {
        switch container {
        case .hls: return true
        case .mp4, .m4a:
            if codecs.isEmpty { return true }
            return codecs.allSatisfy { c in
                let l = c.lowercased()
                return l.hasPrefix("avc1") || l.hasPrefix("hvc1") || l.hasPrefix("hev1") || l.hasPrefix("mp4a") || l.hasPrefix("ec-3") || l.hasPrefix("ac-3")
            }
        case .webm, .other: return false
        }
    }
}

public struct SubtitleTrack: Identifiable, Sendable, Hashable {
    public let id: String
    public let languageCode: String
    public let displayName: String
    public let url: URL
    public let isAutoGenerated: Bool
    public let isTranslation: Bool

    public init(id: String, languageCode: String, displayName: String, url: URL, isAutoGenerated: Bool, isTranslation: Bool = false) {
        self.id = id; self.languageCode = languageCode; self.displayName = displayName
        self.url = url; self.isAutoGenerated = isAutoGenerated; self.isTranslation = isTranslation
    }
}

public struct LanguageOption: Sendable, Hashable, Identifiable {
    public let code: String
    public let name: String
    public var id: String { code }
    public init(code: String, name: String) { self.code = code; self.name = name }
}

public enum SegmentClassification: Sendable, Equatable, Codable { case content, advertisement, unknown }

public enum SegmentCategory: String, Sendable, Codable, CaseIterable, Hashable {
    case sponsor, intro, outro, selfPromotion, interactionReminder

    public var title: String {
        switch self {
        case .sponsor: "Sponsor"
        case .intro: "Intro"
        case .outro: "Outro"
        case .selfPromotion: "Self promotion"
        case .interactionReminder: "Interaction reminder"
        }
    }
}

public struct MediaSegment: Sendable, Equatable {
    public let url: URL?
    public let range: ClosedRange<Duration>?
    public let kind: SegmentClassification
    public let category: SegmentCategory?
    public init(url: URL? = nil, range: ClosedRange<Duration>? = nil, kind: SegmentClassification = .unknown, category: SegmentCategory? = nil) {
        self.url = url; self.range = range; self.kind = kind; self.category = category
    }
}

/// What the provider resolves for playback (ADR §5). Contains no provider-specific types.
public struct PlaybackResource: Sendable, Equatable {
    public let videoID: VideoID
    public let title: String
    public let channelName: String?
    /// HLS master playlists, muxed progressive streams and video-only adaptive streams.
    public let videoStreams: [MediaStream]
    public let audioStreams: [MediaStream]
    public let subtitles: [SubtitleTrack]
    public let translationLanguages: [LanguageOption]
    public let segments: [MediaSegment]
    public let artworkURL: URL?
    public let duration: Duration?
    public let isLive: Bool
    /// When the signed URLs stop being valid (ADR §41, §49).
    public let expiresAt: Date?
    /// Some providers require a matching User-Agent on media requests.
    public let httpUserAgent: String?

    public init(
        videoID: VideoID, title: String, channelName: String? = nil,
        videoStreams: [MediaStream], audioStreams: [MediaStream] = [],
        subtitles: [SubtitleTrack] = [], translationLanguages: [LanguageOption] = [],
        segments: [MediaSegment] = [], artworkURL: URL? = nil, duration: Duration? = nil,
        isLive: Bool = false, expiresAt: Date? = nil, httpUserAgent: String? = nil
    ) {
        self.videoID = videoID; self.title = title; self.channelName = channelName
        self.videoStreams = videoStreams; self.audioStreams = audioStreams
        self.subtitles = subtitles; self.translationLanguages = translationLanguages
        self.segments = segments; self.artworkURL = artworkURL; self.duration = duration
        self.isLive = isLive; self.expiresAt = expiresAt; self.httpUserAgent = httpUserAgent
    }

    public func isExpired(now: Date = .now, leeway: TimeInterval = 30) -> Bool {
        guard let expiresAt else { return false }
        return now.addingTimeInterval(leeway) >= expiresAt
    }

    public func replacing(videoStreams: [MediaStream]? = nil, audioStreams: [MediaStream]? = nil, segments: [MediaSegment]? = nil) -> PlaybackResource {
        PlaybackResource(
            videoID: videoID, title: title, channelName: channelName,
            videoStreams: videoStreams ?? self.videoStreams, audioStreams: audioStreams ?? self.audioStreams,
            subtitles: subtitles, translationLanguages: translationLanguages,
            segments: segments ?? self.segments, artworkURL: artworkURL, duration: duration,
            isLive: isLive, expiresAt: expiresAt, httpUserAgent: httpUserAgent)
    }
}

public enum VideoQuality: Int, Sendable, Codable, CaseIterable, Hashable, Identifiable {
    case auto = 0, p144 = 144, p240 = 240, p360 = 360, p480 = 480, p720 = 720, p1080 = 1080, p1440 = 1440, p2160 = 2160

    public var id: Int { rawValue }
    public var height: Int? { self == .auto ? nil : rawValue }
    public var title: String { self == .auto ? "Auto" : "\(rawValue)p" }

    /// Nearest standard rung at or below `height` (so 1080x1920 portrait content maps via its short side).
    public init?(height: Int) {
        guard let match = VideoQuality.allCases.filter({ $0 != .auto && $0.rawValue <= height }).max(by: { $0.rawValue < $1.rawValue }) else { return nil }
        self = match
    }
}

public struct PlaybackQueue: Sendable, Equatable, Codable {
    public static let maxPrevious = 50
    public static let maxUpcoming = 200

    public var previous: [Video]
    public var current: Video?
    public var upcoming: [Video]

    public init(previous: [Video] = [], current: Video? = nil, upcoming: [Video] = []) {
        self.previous = previous; self.current = current; self.upcoming = upcoming
    }
    public var hasNext: Bool { !upcoming.isEmpty }
    public var hasPrevious: Bool { !previous.isEmpty }
}

public enum PlaybackState: Sendable, Equatable {
    case idle, resolving, loading, ready, playing, paused, buffering, ended
    case failed(PlaybackError)

    public var isActivelyPlaying: Bool { self == .playing || self == .buffering }
}
