import Foundation
import Testing
@testable import ITubeCore

@Suite struct YouTubeParserTests {
    @Test func searchParsesItemsInOrderAndDropsPromotedAndMalformed() throws {
        let items = YouTubeParser.searchItems(try fixtureJSON("search_response"), filter: .all)
        #expect(items.map(\.id) == ["v:dQw4w9WgXcQ", "v:9bZkp7q19f0", "c:UCchan0001", "p:PLabcdefghij"])
    }

    @Test func videoFieldsAreNormalised() throws {
        let items = YouTubeParser.searchItems(try fixtureJSON("search_response"), filter: .videos)
        guard case .video(let v) = items[0] else { Issue.record("expected video"); return }
        #expect(v.title == "First result")
        #expect(v.duration == .seconds(212))
        #expect(v.viewCount == 1_234_567)
        #expect(v.channel?.id == "UCabc123")
        #expect(v.publishedText == "2 years ago")
        #expect(v.thumbnails.allSatisfy { $0.url.scheme == "https" })      // protocol-relative and http upgraded
        guard case .video(let second) = items[1] else { Issue.record("expected video"); return }
        #expect(second.duration == .seconds(3723))
        #expect(second.viewCount == 1_200_000)
        #expect(items.count == 2)                                          // filter keeps videos only
    }

    @Test func channelAndPlaylistRenderers() throws {
        let items = YouTubeParser.searchItems(try fixtureJSON("search_response"), filter: .all)
        guard case .channel(let c) = items[2], case .playlist(let p) = items[3] else { Issue.record("shape"); return }
        #expect(c.name == "A Channel"); #expect(c.subscriberText == "1.5M subscribers"); #expect(c.thumbnailURL?.scheme == "https")
        #expect(p.title == "A Playlist"); #expect(p.videoCountText == "42"); #expect(p.thumbnails.count == 1)
    }

    @Test func continuationToken() throws {
        #expect(YouTubeParser.continuation(try fixtureJSON("search_response")) == "CONT_TOKEN_1")
    }

    @Test func countParsing() {
        #expect(YouTubeParser.count("1,234 views") == 1234)
        #expect(YouTubeParser.count("1.2M views") == 1_200_000)
        #expect(YouTubeParser.count("15K views") == 15_000)
        #expect(YouTubeParser.count("No views") == 0)
        #expect(YouTubeParser.count("garbage") == nil)
        #expect(YouTubeParser.count(nil) == nil)
    }

    @Test func clockDurationParsing() {
        #expect(YouTubeParser.clockDuration("3:32") == .seconds(212))
        #expect(YouTubeParser.clockDuration("1:02:03") == .seconds(3723))
        #expect(YouTubeParser.clockDuration("LIVE") == nil)
        #expect(YouTubeParser.clockDuration("1:2:3:4") == nil)
    }

    @Test func nonHTTPSURLsAreRejected() {
        #expect(YouTubeParser.httpsURL("javascript:alert(1)") == nil)
        #expect(YouTubeParser.httpsURL("file:///etc/passwd") == nil)
        #expect(YouTubeParser.httpsURL("ftp://x.com/a") == nil)
        #expect(YouTubeParser.httpsURL("//i.ytimg.com/a.jpg")?.absoluteString == "https://i.ytimg.com/a.jpg")
        #expect(YouTubeParser.httpsURL("http://i.ytimg.com/a.jpg")?.scheme == "https")
    }

    @Test func playerSnapshotBuildsProviderIndependentResource() throws {
        let now = Date(timeIntervalSince1970: 1_000)
        let snap = try YouTubeParser.playerSnapshot(try fixtureJSON("player_response"), requestedID: "dQw4w9WgXcQ", now: now, userAgent: "UA")
        let r = snap.resource
        #expect(r.duration == .seconds(212))
        #expect(r.expiresAt == now.addingTimeInterval(21_540))
        #expect(r.httpUserAgent == "UA")
        #expect(r.videoStreams.first?.isHLS == true)
        // ciphered itag 22 is skipped (would need JS evaluation); muxed 18 + adaptive 137 + webm 248 remain
        #expect(r.videoStreams.filter { !$0.isHLS }.map(\.id).sorted() == ["137", "18", "248"])
        #expect(r.videoStreams.first { $0.id == "18" }?.isMuxed == true)
        #expect(r.videoStreams.first { $0.id == "137" }?.hasAudio == false)
        #expect(r.audioStreams.map(\.id).sorted() == ["140", "251"])
        #expect(r.videoStreams.first { $0.id == "248" }?.isNativelyPlayable == false)
        #expect(snap.video.viewCount == 987_654)
        #expect(snap.video.channel?.name == "Some Channel")
        #expect(snap.description == "A description.")
        #expect(snap.video.publishedAt != nil)
        #expect(r.artworkURL?.absoluteString.hasSuffix("maxresdefault.jpg") == true)
    }

    @Test func captionTracksAndTranslations() throws {
        let r = try YouTubeParser.playerSnapshot(try fixtureJSON("player_response"), requestedID: "dQw4w9WgXcQ", now: .now, userAgent: nil).resource
        #expect(r.subtitles.map(\.id) == ["en", "en-asr"])
        #expect(r.subtitles[1].isAutoGenerated && !r.subtitles[0].isAutoGenerated)
        #expect(r.subtitles[1].displayName == "English (auto-generated)")
        #expect(r.subtitles.allSatisfy { $0.url.query()?.contains("fmt=vtt") == true })
        #expect(r.translationLanguages.map(\.code) == ["fr", "de"])
    }

    @Test func restrictedAndMismatchedResponsesAreRejected() throws {
        #expect(throws: ProviderError.restricted) {
            try YouTubeParser.playerSnapshot(try fixtureJSON("player_login_required"), requestedID: "dQw4w9WgXcQ", now: .now, userAgent: nil)
        }
        #expect(throws: (any Error).self) {
            try YouTubeParser.playerSnapshot(try fixtureJSON("player_wrong_video"), requestedID: "dQw4w9WgXcQ", now: .now, userAgent: nil)
        }
    }

    @Test func relatedExcludesCurrentAndPromoted() throws {
        let related = YouTubeParser.videos(try fixtureJSON("next_response"), excluding: "dQw4w9WgXcQ")
        #expect(related.map(\.id.rawValue) == ["REL00000001", "REL00000002"])
        #expect(related[0].channel?.name == "Rel Channel")
        #expect(related[0].viewCount == 5000)
    }

    @Test func malformedJSONIsAnErrorNotACrash() {
        #expect(throws: (any Error).self) { try JSONValue.decode(Data("{not json".utf8)) }
        #expect(YouTubeParser.videos(.object([:])).isEmpty)
        #expect(YouTubeParser.searchItems(.array([.null, .string("x")]), filter: .all).isEmpty)
    }

    @Test func deeplyNestedJSONDoesNotOverflow() {
        var node = JSONValue.object(["videoRenderer": .object(["videoId": .string("dQw4w9WgXcQ"), "title": .string("deep")])])
        for _ in 0..<200 { node = .array([node]) }
        #expect(node.descendants(named: "videoRenderer").isEmpty)    // beyond maxDepth: bounded, no stack overflow
    }
}

@Suite struct YouTubeProviderTests {
    private func makeProvider(_ http: MockHTTPClient, auth: any AuthenticationProvider = AnonymousAuthenticationProvider()) -> YouTubeProvider {
        YouTubeProvider(http: http, authentication: auth)
    }

    private func router() -> MockHTTPClient {
        let player = fixture("player_response"), search = fixture("search_response"), next = fixture("next_response")
        return MockHTTPClient { req in
            let path = req.url!.path()
            if path.hasSuffix("/player") { return (player, 200) }
            if path.hasSuffix("/search") { return (search, 200) }
            if path.hasSuffix("/next") { return (next, 200) }
            if path.hasSuffix("/browse") { return (search, 200) }
            return (Data("[]".utf8), 404)
        }
    }

    @Test func searchSendsWebClientBodyAndParses() async throws {
        let http = router()
        let page = try await makeProvider(http).search(SearchRequest(query: "  swift  ", filter: .videos))
        #expect(page.videos.count == 2)
        #expect(page.continuation == "CONT_TOKEN_1")
        let req = try #require(await http.requests.first)
        #expect(req.httpMethod == "POST")
        #expect(req.url?.scheme == "https")
        let body = try #require(JSONSerialization.jsonObject(with: req.httpBody ?? Data()) as? [String: Any])
        #expect(body["query"] as? String == "swift")
        #expect(body["params"] as? String == "EgIQAQ==")
        let client = ((body["context"] as? [String: Any])?["client"] as? [String: Any])
        #expect(client?["clientName"] as? String == "WEB")
    }

    @Test func emptyAndOverlongQueriesNeverHitTheNetwork() async throws {
        let http = router()
        let p = makeProvider(http)
        #expect(try await p.search(SearchRequest(query: "   ")).items.isEmpty)
        #expect(try await p.search(SearchRequest(query: String(repeating: "a", count: 500))).items.isEmpty)
        #expect(await http.requests.isEmpty)
    }

    @Test func playbackResourceUsesIOSClientAndIsCached() async throws {
        let http = router()
        let p = makeProvider(http)
        let r1 = try await p.playbackResource(for: "dQw4w9WgXcQ")
        let r2 = try await p.playbackResource(for: "dQw4w9WgXcQ")
        #expect(r1 == r2)
        #expect(await http.requests.count == 1)                            // second call served from cache
        let req = try #require(await http.requests.first)
        #expect(req.value(forHTTPHeaderField: "X-YouTube-Client-Name") == "5")
        #expect(req.value(forHTTPHeaderField: "User-Agent")?.hasPrefix("com.google.ios.youtube/") == true)
        #expect(req.value(forHTTPHeaderField: "Cookie") == nil)            // anonymous playback never carries cookies
    }

    @Test func invalidateForcesFreshResolution() async throws {
        let http = router()
        let p = makeProvider(http)
        _ = try await p.playbackResource(for: "dQw4w9WgXcQ")
        await p.invalidatePlaybackResource(for: "dQw4w9WgXcQ")
        _ = try await p.playbackResource(for: "dQw4w9WgXcQ")
        #expect(await http.requests.count == 2)
    }

    @Test func malformedIDsAreRejectedBeforeAnyRequest() async {
        let http = router()
        await #expect(throws: ProviderError.notFound) { try await makeProvider(http).playbackResource(for: "../../etc/passwd") }
        #expect(await http.requests.isEmpty)
    }

    @Test func detailsCombinePlayerAndRelated() async throws {
        let d = try await makeProvider(router()).details(for: "dQw4w9WgXcQ")
        #expect(d.video.title == "Test Video")
        #expect(d.related.map(\.id.rawValue) == ["REL00000001", "REL00000002"])
    }

    @Test func relatedFailureIsNonFatal() async throws {
        let player = fixture("player_response")
        let http = MockHTTPClient { req in req.url!.path().hasSuffix("/player") ? (player, 200) : (Data(), 500) }
        let d = try await makeProvider(http).details(for: "dQw4w9WgXcQ")
        #expect(d.related.isEmpty)
    }

    @Test func httpNotFoundMapsToProviderError() async {
        let http = MockHTTPClient { _ in (Data(), 404) }
        await #expect(throws: ProviderError.notFound) { try await makeProvider(http).playbackResource(for: "dQw4w9WgXcQ") }
    }

    @Test func invalidJSONBecomesParsingError() async {
        let http = MockHTTPClient { _ in (Data("<html>".utf8), 200) }
        await #expect(throws: (any Error).self) { try await makeProvider(http).playbackResource(for: "dQw4w9WgXcQ") }
    }

    @Test func personalisedFeedsRequireSignIn() async {
        let p = makeProvider(router())
        await #expect(throws: ProviderError.authenticationRequired) { try await p.recommended() }
        await #expect(throws: ProviderError.authenticationRequired) { try await p.subscriptionsFeed() }
    }

    @Test func signedInRequestsCarryAuthOnlyToYouTubeHosts() async throws {
        let secrets = InMemorySecrets()
        let auth = YouTubeAuthentication(secrets: secrets, clock: { Date(timeIntervalSince1970: 1_700_000_000) })
        try await auth.signIn(cookies: [
            StoredCookie(name: "SAPISID", value: "abc123", domain: ".youtube.com"),
            StoredCookie(name: "SID", value: "sid", domain: ".google.com"),
            StoredCookie(name: "tracking", value: "x", domain: ".youtube.com"),     // not allow-listed: dropped
        ])
        let http = router()
        _ = try await makeProvider(http, auth: auth).recommended()
        let req = try #require(await http.requests.first)
        #expect(req.value(forHTTPHeaderField: "Authorization")?.hasPrefix("SAPISIDHASH 1700000000_") == true)
        #expect(req.value(forHTTPHeaderField: "Cookie")?.contains("SAPISID=abc123") == true)
        #expect(req.value(forHTTPHeaderField: "Cookie")?.contains("tracking") == false)

        var other = URLRequest(url: URL(string: "https://evil.example.com/")!)
        other = await auth.authorize(other)
        #expect(other.value(forHTTPHeaderField: "Cookie") == nil)
        #expect(other.value(forHTTPHeaderField: "Authorization") == nil)
    }
}

@Suite struct YouTubeAuthenticationTests {
    @Test func sapisidHashMatchesKnownVector() {
        #expect(YouTubeAuthentication.sapisidHash(sapisid: "abc123", origin: "https://www.youtube.com", timestamp: 1_700_000_000)
                == "SAPISIDHASH 1700000000_9e5071f149fc514366f78b22d1a169786d40ed32")
    }

    @Test func signInWithoutAuthCookieIsRejected() async {
        let auth = YouTubeAuthentication(secrets: InMemorySecrets())
        await #expect(throws: ProviderError.authenticationRequired) {
            try await auth.signIn(cookies: [StoredCookie(name: "PREF", value: "x", domain: ".youtube.com")])
        }
        #expect(await auth.isSignedIn == false)
    }

    @Test func expiredCookiesAreIgnoredAndSignOutClearsStorage() async throws {
        let secrets = InMemorySecrets()
        let auth = YouTubeAuthentication(secrets: secrets)
        await #expect(throws: ProviderError.authenticationRequired) {
            try await auth.signIn(cookies: [StoredCookie(name: "SAPISID", value: "x", domain: ".youtube.com", expires: Date(timeIntervalSince1970: 1))])
        }
        try await auth.signIn(cookies: [StoredCookie(name: "SAPISID", value: "x", domain: ".youtube.com")])
        #expect(await auth.isSignedIn)
        #expect(secrets.read(account: "youtube.cookies.v1") != nil)
        await auth.signOut()
        #expect(await auth.isSignedIn == false)
        #expect(secrets.read(account: "youtube.cookies.v1") == nil)
    }

    @Test func sessionSurvivesRelaunch() async throws {
        let secrets = InMemorySecrets()
        try await YouTubeAuthentication(secrets: secrets).signIn(cookies: [StoredCookie(name: "SAPISID", value: "x", domain: ".youtube.com")])
        #expect(await YouTubeAuthentication(secrets: secrets).isSignedIn)
    }
}
